### ISSUE TITLE
PWC - 1138 | Bug | Status not getting ported on WD

### ISSUE THREAD

**Issue by princyjv** [talview/proview-sample-android#30]
<html>
<body>
<div class="elementToProof" data-identifyelement="333" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">Hi Team, </div><div class="elementToProof" data-identifyelement="334" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br data-identifyelement="335" style="box-sizing: border-box;"></div><div class="elementToProof" data-identifyelement="336" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">The status of screening is not getting ported on workday from Talview and it has been more than 24 hours. </div><div class="elementToProof" data-identifyelement="337" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">PFB few of those cases : </div><div class="elementToProof" data-identifyelement="338" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br data-identifyelement="339" style="box-sizing: border-box;"></div><div class="elementToProof" data-identifyelement="340" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><div class="ticket-details-table-wrapper" data-identifyelement="341" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; overflow: auto; white-space: normal;">

Candidate ID | REQ ID
-- | --
C000009543185 | 476722WD
C000009551242 | 476722WD
C000009544542 | 476722WD
C000000659735 | 476722WD
C000007218074 | 476722WD
C000008843425 | 476722WD
C000008932776 | 476722WD
C000006479229 | 483971WD
C000009572888 | 483971WD

</div></div><br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>
<div class="elementToProof" data-identifyelement="414" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">Please note that none of the candidates who are rejected on Talview for the above two REQ ID is being ported to workday, I have mentioned few candidate IDs out of all. Also, PFB the numeric figure of such cases : </div><div class="elementToProof" data-identifyelement="415" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br data-identifyelement="416" style="box-sizing: border-box;"></div><div class="elementToProof" data-identifyelement="417" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><div class="ContentPasted1" data-identifyelement="418" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; box-shadow: none; border-radius: 0.285714rem 0.285714rem 0px 0px; bottom: 0px;"><div class="ContentPasted1" data-identifyelement="419" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; flex-flow: wrap; align-items: stretch;"><div data-identifyelement="420" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; padding: 1rem; display: inline-block;"></div></div></div><div data-identifyelement="421" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; box-shadow: none; border-radius: 0px 0px 0.285714rem 0.285714rem; border-top: rgba(34, 36, 38, 0.15); bottom: 0px;"></div><div class="ContentPasted1" data-identifyelement="422" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; box-shadow: none; border-radius: 0.285714rem 0.285714rem 0px 0px; bottom: 0px;"><div class="ContentPasted1" data-identifyelement="423" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; flex-flow: wrap; align-items: stretch;"><div data-identifyelement="424" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; padding: 1rem; display: inline-block;"></div></div></div><div data-identifyelement="425" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; box-shadow: none; border-radius: 0px 0px 0.285714rem 0.285714rem; border-top: rgba(34, 36, 38, 0.15); bottom: 0px;"></div><div class="ticket-details-table-wrapper" data-identifyelement="426" style="box-sizing: border-box; word-break: break-word; overflow-wrap: break-word; overflow: auto; white-space: normal;">

REQ ID | Rejected | In process | Total Candidates |  
-- | -- | -- | -- | --
476722WD | 47 | 7 | 54 |  
483971WD | 2 | 1 | 3 |  

</div></div>
</body>
</html>

We are getting no logs in the database

![Image](https://github.com/talview/proview-sample-android/assets/136870289/94d1f064-ec4a-4a78-9d7b-d54f4be79e15)

**Comment by princyjv** [comment]
PR under review: https://github.com/talview/delivery-pwc/pull/437

**Comment by princyjv** [comment]
@ayyappa Please validate this on staging
@Jithu7892 Please help

**Comment by Jithu7892** [comment]
Hi @princyjv - Tested form porting functionality. Below are my observation. 
1.Please can you please check why form is not porting to workday for below requisition? 
1.CID -C000009563081
BR -444455WD



![Image](https://github.com/talview/proview-sample-android/assets/125969645/029b2eb7-694d-4e3a-9f74-cc614e4abcf9)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/9c7738a1-13e6-4c09-b4c0-7cc78cb38a01)



Working 
Without form 
1.CID -C000009563077
BR- 444455WD
![Image](https://github.com/talview/proview-sample-android/assets/125969645/8b4820b5-3945-4cef-8b09-7424cb4e1e09)

with form
2.
CID -C000009563076
BR462489WD

**Comment by princyjv** [comment]
Deployed the change: https://github.com/talview/delivery-pwc/pull/440
@Jithu7892 can you please validate

**Comment by swaraj-talview** [comment]
Hi @princyjv @Jithu7892 ,

can we please have any closure update on this or any TAT as it was raised 6 days ago and customer is following up continuously

**Comment by Jithu7892** [comment]
@princy  - Validated on staging. functionality working as per expected.
BR with Evaluation form 
1.Candidate is rejected in Screening after filling evaluation form.  
CID - C000009625482
BR -462489WD

![Image](https://github.com/talview/proview-sample-android/assets/125969645/abd3dc2a-93fd-4b92-93fd-7e7917ff5ada)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/2dd147e6-d6f5-4e47-80ed-1cb33ae38a7f)

2.Candidate rejected by filling evacuation form with comment.
CID -C000009625483
BR -462489WD

![Image](https://github.com/talview/proview-sample-android/assets/125969645/6b25b9c3-6f8f-4227-a446-fb6aa2919e4d)


![Image](https://github.com/talview/proview-sample-android/assets/125969645/9e1cb59b-d5c5-47da-9c47-357b832759c3)


3. Candida rejected without filling evaluation form 
BR -462489WD
C000009625484


![Image](https://github.com/talview/proview-sample-android/assets/125969645/a25cd06a-a761-4495-b697-8de7800626d7)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/1bf72658-cb69-4d91-9059-a0d2fe86b514)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/267d12be-1b5b-499e-b8ec-7e9a2e704c8d)

4.Form porting functionality working To1 and Tp2 from pofrting functionality working as per expected


![Image](https://github.com/talview/proview-sample-android/assets/125969645/42dd14c6-844c-46ec-927a-2c91aeb0c197)

Old requisition 
1.Candidate is rejected for Screening after filling evolution form.

CID - C000009625487
RR -444455WD



![Image](https://github.com/talview/proview-sample-android/assets/125969645/f7972552-df4c-4592-a1c9-504f86252733)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/7e240b32-d024-4a72-9ff5-8ce22991e36c)
2.Candidate is rejected without filling evaluation form 
CID -C000009625488
RR -444455WD


![Image](https://github.com/talview/proview-sample-android/assets/125969645/d511438e-db51-4cf5-9c3f-89d45d58f024)

3.Candidate is selected and rejected in Tp2 form 


![Image](https://github.com/talview/proview-sample-android/assets/125969645/017a06cf-8537-4c36-8e86-4a379001c3ab)

4.Candidate is rejected in regulated.
CID -C000009625494 
BR -462645WD


![Image](https://github.com/talview/proview-sample-android/assets/125969645/dff84529-92cd-4eb5-829a-1a153dff728e)

**Comment by princyjv** [comment]
Prod PR under review: https://github.com/talview/delivery-pwc/pull/443

**Comment by princyjv** [comment]
@Jithu7892 can you please validate in Production

**Comment by Jithu7892** [comment]
Hi @princyjv - Tested on prod, working as per expected.
1.Candidate is created and ported to talview.
CID -C000009653728
BR -476722WD


![Image](https://github.com/talview/proview-sample-android/assets/125969645/0917a39c-f7f0-431b-9118-0cfc80c5cfc7)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/c728fad3-71a2-403b-8a81-7108aaa5b8a6)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/056f628c-7c97-43ca-9f9a-0f1e9d4d51fd)

2.Form porting functionality working as per expected.



![Image](https://github.com/talview/proview-sample-android/assets/125969645/18e0b729-dd3b-403f-8891-6d5d9d0b1d0c)







3.New requisition -disposition form is updating as per expected
CID -C000009654076



![Image](https://github.com/talview/proview-sample-android/assets/125969645/2c29128a-7b74-4d0e-8949-b2440aa1bb58)



![Image](https://github.com/talview/proview-sample-android/assets/125969645/38207028-b5e3-494d-88ae-b37db971f549)

Regulated 
CID - C000009654509
BR- 484813WD
![Image](https://github.com/talview/proview-sample-android/assets/125969645/d2e4c151-1b0e-4af3-a392-227224b13822)

**Comment by Jithu7892** [comment]
@princy - Please do recon for above candidate and impacted candidate.

**Comment by princyjv** [comment]
@Jithu7892 
reconciliation done for all the candidates please validate

**Comment by Jithu7892** [comment]
Hi @princy - Validated on prod account, Dispositions status is ported to workday successfully and recon is done for all the done candidates.


![Image](https://github.com/talview/proview-sample-android/assets/125969645/e62aa331-c2f3-4f04-a0d5-65d1599e2ae4)
